config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index"
  resources :boards, only: [:index, :new] do
    collection do
      get 'cpu'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  end

  def new
  end

  def cpu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/cpu.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="wrapper_cpu">
      <div class="table_side">
        <table border="1" style="border-collapse: collapse" bordercolor="black" bgcolor="green" width="600" height="600" class="table"  id="table">
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"><div class="black-stone"></div></td>
            <td height="75"><div class="white-stone"></div></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"><div class="white-stone"></div></td>
            <td height="75"><div class="black-stone"></div></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
        </table>
      </div>

      <div class="infomation_side">
        <br>
        <br>
        <input type="button" value="Pass" id="pass" style="font-size:20px;width:60px;height:40px">
        <br>
        <br>
        <!- 石の数 ->
          <div class="stone_number">
            <div class="player">Player</div>
            <div class="white-stone"></div>
            <div id="white_num">
              <div id="num">2</div>
            </div>
          </div>
          <div class="stone_number">
            <div class="player">CPU</div>
            <div class="black-stone"></div>
            <div id="black_num">
              <div id="num">2</div>
            </div>
          </div>
        <br>
        <div id="result"></div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div>
        <%= link_to 'HOME', "/", class: "home-link"  %>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag 'cpu/application' %>
  </body>
</html>

app/views/boards/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Othello</title>
</head>

<body id="index_body">
 <div id="title_name">Othello</div>
  <%= link_to "2人で対戦", new_board_path, class: "game_start" %>
  <br>
  <br>
  <%= link_to "CPUと対戦", cpu_boards_path, class: "game_start" %>
</body>
</html>

app/views/boards/new.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="wrapper">
      <div class="table_side">
        <table border="1" style="border-collapse: collapse" bordercolor="black" bgcolor="green" width="600" height="600" class="table"  id="table">
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"><div class="black-stone"></div></td>
            <td height="75"><div class="white-stone"></div></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"><div class="white-stone"></div></td>
            <td height="75"><div class="black-stone"></div></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
          <tr>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
            <td height="75"></td>
          </tr>
        </table>
      </div>

      <div class="infomation_side">
        <br>
        <div id="player_turn">White turn</div>
        <br>
        <input type="button" value="Pass" id="pass" style="font-size:20px;width:60px;height:40px">
        <br>
        <br>
        <!- 石の数 ->
        <div class="stone_number">
          <div class="player">Player１　</div>
          <div class="white-stone"></div>
          <div id="white_num">
            <div id="num">2</div>
          </div>
        </div>
        <div class="stone_number">
          <div class="player">Player２　</div>
          <div class="black-stone"></div>
          <div id="black_num">
            <div id="num">2</div>
          </div>
        </div>
        <br>
        <div id="result"></div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div>
        <%= link_to 'HOME', "/", class: "home-link"  %>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag 'pvp/application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Othello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>